# Generated by Django 3.0.5 on 2020-04-16 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='tasks',
            new_name='task',
        ),
    ]
