# Generated by Django 3.0.5 on 2020-04-20 13:36

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20200416_2050'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='todo',
            managers=[
                ('objecs', django.db.models.manager.Manager()),
            ],
        ),
    ]
