# Generated by Django 3.0.5 on 2020-04-20 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20200420_2236'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='todo',
            managers=[
            ],
        ),
    ]
